### PR TITLE
Script reader possible memory leak fix.

### LINKED ISSUE #801: [ScriptReader] Undisposed -> Leak?
`NBitcoin.ScriptReader` is not `IDisposable`, but it contains inner `Stream`, often `MemoryStream`. Should not this inner stream be disposed?

### PR DESCRIPTION
**Pull request by noescape00**
Made ScriptReader disposable and changed every ScriptReader's usage in order to dispose it after it's not needed. 

Fix #801

### CODE REVIEW

**Comment by fassadlr** [comment]
@noescape00 Before I merge, please confirm that you have run the node in test and main to ensure that its still syncing etc?

**Comment by noescape00** [comment]
@fassadlr
Sure, I confirm. 
I always sync before pushing any commit when I do something non-cosmetic.

**Comment by fassadlr** [comment]
Thanks @noescape00!

Ah I see there's some conflicts now.

**Comment by noescape00** [comment]
Ok, I'm fixing it.

File: src/NBitcoin/Script.cs [hunk 1]
```diff
@@ -807,8 +814,10 @@ private static BitcoinStream CreateHashWriter(HashVersion version)
 
         public IEnumerable<Op> ToOps()
         {
-            ScriptReader reader = new ScriptReader(_Script);
-            return reader.ToEnumerable();
+            using (ScriptReader reader = new ScriptReader(_Script))
+            {
+                return reader.ToEnumerable().ToList();
```
Comment (bokobza) [inline src/NBitcoin/Script.cs]: Does `return reader.ToEnumerable();` not work here?

File: src/NBitcoin/ScriptReader.cs [hunk 2]
```diff
@@ -748,9 +748,12 @@ public IEnumerable<Op> ToEnumerable()
...
             Op code;
             while((code = Read()) != null)
-            {
                 yield return code;
-            }
+        }
+
+        public void Dispose()
+        {
+            this._Inner.Dispose();
```
Comment (bokobza) [inline src/NBitcoin/ScriptReader.cs]: what happens if the object is null?

Comment (noescape00) [reply src/NBitcoin/ScriptReader.cs]: Hmm. 
I assumed that check in the constructor would be enough. 
But it is possible to set it to null after the creation so I'll add a null check. 
Thx for pointing that out.

File: src/NBitcoin/Script.cs (hunk 1 above)
Comment (noescape00) [reply src/NBitcoin/Script.cs]: No. It does git disposed before enumeration starts. 

But we can afford loading it as a whole list- scripts are small anyway and in every case that enumerable would enumerate it to the end so all of it will eventually be loaded.

Comment (bokobza) [reply src/NBitcoin/Script.cs]: ah yes fair enough.

**Comment by dangershony** [comment]
I agree its very hard to review this @noescape00 its impossible to know if you made logic changes without a lot of work from the reviewer. 
Is there anything we can do to fix this?

File: src/NBitcoin/ScriptReader.cs [hunk 3]
```diff
@@ -696,46 +696,46 @@ public bool IsSmallInt
...
+    public class ScriptReader : IDisposable
     {
         private readonly Stream _Inner;
+
         public Stream Inner
         {
             get
             {
-                return _Inner;
+                return this._Inner;
```
Comment (dangershony) [inline src/NBitcoin/ScriptReader.cs]: If you are already making some changes here then rename `_Inner` to `inner`

**Comment by dangershony** [comment]
Ok after Jeremys little trick to append `?w=1` to the url on the review page, that removes all white spaces.
I am all good on this review.

File: src/NBitcoin/ScriptReader.cs (hunk 3 above)
Comment (noescape00) [reply src/NBitcoin/ScriptReader.cs]: Fixed.
